name: dockle

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  dockle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dockle (dss-postgres)
        uses: ./
        with:
          image: 'ubuntu:latest'
          exit-level: 'info'
